# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql:8.0.31
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-fromrevious-series.html#upgrade-caching-sha2assword
    # (this is just an example, not intended to be a production configuration)
#    command: --default-authenticationlugin=mysql_native_password
#    restart: always
    ports:
      - "3306:3306"
    container_name: mysql
    environment:
      MYSQL_USER: valescasudo
      MYSQL_DATABASE: salao_db
      MYSQL_PASSWORD: valescasudo
      MYSQL_ROOT_PASSWORD: root
  jaeger:
    image: jaegertracing/all-in-one:1.39
    container_name: jaeger
    ports:
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "5778:5778"
    - "16686:16686"
    - "4317:4317"
    - "4318:4318"
    - "14250:14250"
    - "14268:14268"
    - "14269:14269"
    - "9411:9411"
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080